name: dotbook
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.2+1

environment:
  sdk: ^3.10.0

dependencies:
  cupertino_icons: ^1.0.8
  epubx: ^4.0.0
  external_path: ^2.2.0
  file_picker: ^10.3.7
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^6.0.0
  flutter_spinkit: ^5.2.2
  flutter_widget_from_html: ^0.17.1
  get: ^4.7.3
  package_info_plus: ^9.0.0
  path: ^1.9.1
  pdfx: ^2.9.2
  permission_handler: ^12.0.1
  url_launcher: ^6.3.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo_icon.png"


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/brand/dotbook_logo.png
    - assets/icon/logo_icon.png
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
